name: Check Linux Submodule Clean Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Get Commit Hash of Submodule
        run: linux_commit_hash=$(git rev-parse HEAD:linux)
      - name: Echo Submodule Commit Hash
        run: echo $linux_commit_hash
