name: Check Linux Submodule Clean Build

on:
  push:
    paths: "linux"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check Clean Build
        run: |
          ./install-deps.sh;
          linux_commit_hash=$(git rev-parse HEAD:linux);
          wget https://github.com/seanK200/linux/archive/${linux_commit_hash}.zip;
          unzip -q ${linux_commit_hash}.zip;
          ./build-linux.sh ./linux-${linux_commit_hash} tinyconfig;
